[2023-10-01T02:29:48.034+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_train_dag.data_load scheduled__2023-09-29T01:00:00+00:00 [queued]>
[2023-10-01T02:29:48.037+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_train_dag.data_load scheduled__2023-09-29T01:00:00+00:00 [queued]>
[2023-10-01T02:29:48.037+0300] {taskinstance.py:1359} INFO - Starting attempt 12 of 12
[2023-10-01T02:29:48.104+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): data_load> on 2023-09-29 01:00:00+00:00
[2023-10-01T02:29:48.108+0300] {standard_task_runner.py:57} INFO - Started process 23670 to run task
[2023-10-01T02:29:48.111+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dummy_train_dag', 'data_load', 'scheduled__2023-09-29T01:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_for_model_train.py', '--cfg-path', '/tmp/tmpeqi24j4u']
[2023-10-01T02:29:48.119+0300] {standard_task_runner.py:85} INFO - Job 42: Subtask data_load
[2023-10-01T02:29:48.167+0300] {task_command.py:415} INFO - Running <TaskInstance: dummy_train_dag.data_load scheduled__2023-09-29T01:00:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-01T02:29:48.232+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@gmail.com' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dummy_train_dag' AIRFLOW_CTX_TASK_ID='data_load' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T01:00:00+00:00'
[2023-10-01T02:29:48.233+0300] {test_dag_for_model_train.py:55} INFO - Postgres connection initializing.
[2023-10-01T02:29:48.244+0300] {base.py:73} INFO - Using connection ID 'pg_connection' for task execution.
[2023-10-01T02:29:48.250+0300] {test_dag_for_model_train.py:60} INFO - Taking data from Postgres.
[2023-10-01T02:29:48.258+0300] {logging_mixin.py:151} WARNING - /home/dsbulgako1/my_repos/mlops_project/dags/test_dag_for_model_train.py:61 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-01T02:29:48.321+0300] {test_dag_for_model_train.py:63} INFO - S3 connection initializing.
[2023-10-01T02:29:48.332+0300] {base.py:73} INFO - Using connection ID 's3_connector' for task execution.
[2023-10-01T02:29:48.333+0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='s3_connector', conn_type='aws') credentials retrieved from login and password.
[2023-10-01T02:29:48.372+0300] {configprovider.py:949} INFO - Found endpoint for s3 via: config_global.
[2023-10-01T02:29:48.380+0300] {test_dag_for_model_train.py:68} INFO - S3 data uploading.
[2023-10-01T02:29:48.777+0300] {test_dag_for_model_train.py:71} INFO - Data uploading finished.
[2023-10-01T02:29:48.778+0300] {python.py:194} INFO - Done. Returned value was: None
[2023-10-01T02:29:48.791+0300] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dummy_train_dag, task_id=data_load, execution_date=20230929T010000, start_date=20230930T232948, end_date=20230930T232948
[2023-10-01T02:29:48.807+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-01T02:29:48.825+0300] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
