[2023-10-22T20:49:24.045+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dm1trybu.train_rf scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:49:24.052+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dm1trybu.train_rf scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:49:24.052+0300] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-10-22T20:49:24.063+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): train_rf> on 2023-10-21 09:45:00+00:00
[2023-10-22T20:49:24.068+0300] {standard_task_runner.py:57} INFO - Started process 213049 to run task
[2023-10-22T20:49:24.075+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dm1trybu', 'train_rf', 'scheduled__2023-10-21T09:45:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/final_dag_3_models.py', '--cfg-path', '/tmp/tmp92t_fvd4']
[2023-10-22T20:49:24.078+0300] {standard_task_runner.py:85} INFO - Job 111: Subtask train_rf
[2023-10-22T20:49:24.174+0300] {task_command.py:415} INFO - Running <TaskInstance: dm1trybu.train_rf scheduled__2023-10-21T09:45:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-22T20:49:24.361+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@bk.ru' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dm1trybu' AIRFLOW_CTX_TASK_ID='train_rf' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T09:45:00+00:00'
[2023-10-22T20:49:24.397+0300] {s3.py:1359} INFO - This function shadows the 'download_file' method of S3 API, but it is not the same. If you want to use the original method from S3 API, please call 'S3Hook.get_conn().download_file()'
[2023-10-22T20:49:24.397+0300] {s3.py:1365} INFO - Downloading source S3 file from Bucket mlops-project with path dm1trybu/datasets/X_train.pkl
[2023-10-22T20:49:24.414+0300] {base_aws.py:553} WARNING - Unable to find AWS Connection ID 's3_connection', switching to empty.
[2023-10-22T20:49:24.421+0300] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2023-10-22T20:49:24.711+0300] {credentials.py:1254} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2023-10-22T20:49:27.488+0300] {configprovider.py:949} INFO - Found endpoint for s3 via: config_global.
[2023-10-22T20:49:27.814+0300] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/dags/final_dag_3_models.py", line 224, in train_model
    file = s3_hook.download_file(key=f"{NAME}/datasets/{name}.pkl",
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 136, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1375, in download_file
    raise e
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1368, in download_file
    s3_obj = self.get_key(key, bucket_name)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 136, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 922, in get_key
    obj.load()
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/boto3/resources/factory.py", line 564, in do_action
    response = action(self, *args, **kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
[2023-10-22T20:49:27.829+0300] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dm1trybu, task_id=train_rf, execution_date=20231021T094500, start_date=20231022T174924, end_date=20231022T174927
[2023-10-22T20:49:27.843+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 111 for task train_rf (An error occurred (404) when calling the HeadObject operation: Not Found; 213049)
[2023-10-22T20:49:27.879+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T20:49:27.915+0300] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
