[2023-10-22T20:30:33.366+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:30:33.371+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:30:33.371+0300] {taskinstance.py:1359} INFO - Starting attempt 5 of 8
[2023-10-22T20:30:33.377+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): init> on 2023-10-21 09:45:00+00:00
[2023-10-22T20:30:33.381+0300] {standard_task_runner.py:57} INFO - Started process 209197 to run task
[2023-10-22T20:30:33.384+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dm1trybu', 'init', 'scheduled__2023-10-21T09:45:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/final_dag_3_models.py', '--cfg-path', '/tmp/tmpfl6yrmh8']
[2023-10-22T20:30:33.385+0300] {standard_task_runner.py:85} INFO - Job 99: Subtask init
[2023-10-22T20:30:33.430+0300] {task_command.py:415} INFO - Running <TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-22T20:30:33.495+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@bk.ru' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dm1trybu' AIRFLOW_CTX_TASK_ID='init' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T09:45:00+00:00'
[2023-10-22T20:30:33.496+0300] {final_dag_3_models.py:72} INFO - Initializing dag and collecting meta-data...
[2023-10-22T20:30:33.496+0300] {final_dag_3_models.py:81} INFO - Trying to set new experiment...
[2023-10-22T20:30:33.792+0300] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-10-22T20:30:33.793+0300] {migration.py:216} INFO - Will assume transactional DDL.
[2023-10-22T20:30:33.810+0300] {final_dag_3_models.py:89} INFO - Experiment 'dm1trybu' already exists in MLFlow.
[2023-10-22T20:30:33.810+0300] {final_dag_3_models.py:93} INFO - Creating parent run in MLFlow.
[2023-10-22T20:30:33.811+0300] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/dags/final_dag_3_models.py", line 96, in init
    experiment_id=metrics["experiment_id"],
KeyError: 'experiment_id'
[2023-10-22T20:30:33.822+0300] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dm1trybu, task_id=init, execution_date=20231021T094500, start_date=20231022T173033, end_date=20231022T173033
[2023-10-22T20:30:33.833+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 99 for task init ('experiment_id'; 209197)
[2023-10-22T20:30:33.877+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T20:30:33.900+0300] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
